
# general configuration
url: https://curtis.hu
baseurl: ''

compass:
  logo: "/assets/logo.png"
  author: "Curtis Hu"
  include_content: false
  include_analytics: true
  # Twitter @username (as defined by the Twitter Card specs)
  # twitter: "compass"

exclude: ["CNAME", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

markdown: kramdown
highlighter: rouge

permalink: pretty
